# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_key', models.CharField(max_length=256)),
                ('image_key_match', models.CharField(max_length=256)),
                ('captcha_image', models.CharField(max_length=256)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaptchaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_key', models.CharField(max_length=256)),
                ('captcha_image', models.CharField(max_length=256)),
                ('captcha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_crispy_jcaptcha.Captcha')),
            ],
        ),
    ]
